name: Gradle Precommit and Assemble
on: [pull_request]

jobs:
  precommit:
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: Run Gradle (precommit)
        run: |
          ./gradlew javadoc precommit --parallel
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          colima start
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
      - name: Run Gradle (assemble)
        run: |
          ./gradlew assemble --parallel
